version: '3.8'

services:
  # Serviço do Django
  web:
    build: .
    container_name: newlife_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_URL=${DATABASE_URL}
      - CONTACT_EMAIL=${CONTACT_EMAIL}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - SECURE_SSL_REDIRECT=False
      - SESSION_COOKIE_SECURE=False
      - CSRF_COOKIE_SECURE=False
      - SECURE_HSTS_SECONDS=0
      - X_FRAME_OPTIONS=DENY
    networks:
      - newlife_network
    restart: unless-stopped

  # Serviço Nginx para produção (opcional)
  nginx:
    image: nginx:alpine
    container_name: newlife_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web
    networks:
      - newlife_network
    restart: unless-stopped
    profiles:
      - production

volumes:
  static_volume:
    driver: local

networks:
  newlife_network:
    driver: bridge
