# Generated by Django 5.2.3 on 2025-07-09 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icone', models.CharField(blank=True, help_text="Ícone da categoria (ex: 'bi bi-heart', 'fas fa-leaf')", max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição da categoria', null=True)),
                ('campos_visiveis', models.JSONField(blank=True, default=dict, help_text="Configuração de quais campos devem ser exibidos para produtos desta categoria. Exemplo: {'composicao': True, 'contraindicacao': True, 'modo_uso': True}")),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='produtos.categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('link_compra', models.URLField(help_text='Link externo para compra do produto')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('descricao', models.TextField()),
                ('beneficios', models.TextField(help_text='Lista de benefícios separados por linha')),
                ('composicao', models.TextField(help_text='Composição detalhada do produto')),
                ('contraindicacao', models.TextField(help_text='Contraindicações e precauções')),
                ('modo_uso', models.TextField(help_text='Instruções de uso do produto')),
                ('destaque', models.BooleanField(default=False, help_text='Marcar para exibir na página inicial')),
                ('lancamento', models.BooleanField(default=False, help_text='Marcar como produto lançamento')),
                ('mais_vendido', models.BooleanField(default=False, help_text='Marcar como produto mais vendido')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
