# Generated by Django 5.2.3 on 2025-07-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, help_text="Ícone da categoria (ex: 'bi bi-heart', 'fas fa-leaf')", max_length=255, null=True),
        ),
    ]
