# Generated by Django 5.2.3 on 2025-07-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_categoria_nome_alter_categoria_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
