# Generated by Django 5.2.4 on 2025-08-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, help_text='Marcar se o produto está disponível para exibição', verbose_name='Disponível'),
        ),
    ]
